spring:
  redis:
    cluster:
      nodes: # 配置集群地址
        - 127.0.0.1:7000
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
        - 127.0.0.1:7007